---
title: "MATH167R: Statistical Programming with R"
subtitle: "Fall 2024"
tbl-colwidths: [5,10,20,10,10,10]
format: html
draft: false
---

::: column-screen-inset-right
| Week | Date   | Topic                                 | Slides | Check-in | Lab |
|:----:|--------|---------------------------------------|:------:|:--------:|:---:|
|  1   | W 8/21 | Course Overview and Introduction to R |    [Slides 01](slides/01_overview.html){.label .label-green}          |                                                               | [Lab 01](labs/01_lab.html){.label .label-red} |
|  2   | M 8/26 | R fundamentals                        | [Slides 02](slides/02_objects-classes.html){.label .label-green}        |  [Check-in 01](checkins/01_checkin.html){.label .label-purple}        |     |
|      | W 8/28 | R fundamentals                        | [Slides 03](slides/03_functions-vectors-matrices.html){.label .label-green}       |          |   [Lab 02](labs/02_lab.html){.label .label-red}   |
|  3   | M 9/2  | *Labor Day - No class*                       |        |          |     |
|      | W 9/4 | R fundamentals               |  [Slides 04](slides/04_lists-data-frames.html){.label .label-green}      |          |     |
|  4   | M 9/9 | Exploring data with R                 |   [Slides 05](slides/05_exploring-data.html){.label .label-green}        |        |   [Lab 03](labs/03_lab.html){.label .label-red}    |
|      | W 9/11 | Exploring data with R                    |   [Slides 06](slides/06_factors-groups.html){.label .label-green}      |  [Check-in 02](checkins/02_checkin.html){.label .label-purple} |                  |     |
|  5   | M 9/16 | Data visualization                    | [Slides 07](slides/07_visualizing-data.html){.label .label-green}        |          |     |
|      | W 9/18 | Data visualization                    |   [Slides 08](slides/08_advanced-visualization.html){.label .label-green}      |          |  [Lab 04](labs/04_lab.html){.label .label-red}   |
|  6   | M 9/23 | Data manipulation and management      | [Slides 09](slides/09_merging-data.html){.label .label-green}        | [Check-in 03](checkins/03_checkin.html){.label .label-purple}       |     |
|      | W 9/25 | Data manipulation and management      |  [Slides 10](slides/10_data-management.html){.label .label-green}       |          |     |
|  7   | M 9/30  | Data manipulation and management                      | [Slides 11](slides/11_spatial-data.html){.label .label-green}         |          |     |
|      | W 10/2  | Programming basics                    |  [Slides 12](slides/12_programming-basics.html){.label .label-green}        | [Check-in 04](checkins/04_checkin.html){.label .label-purple}         |   [Lab 05](labs/05_lab.html){.label .label-red}      |
|  8   | M 10/7 | Programming basics                    |  [Slides 13](slides/13_functions-loops.html){.label .label-green}       |   [Check-in 05](checkins/05_checkin.html){.label .label-purple}          |     |
|      | W 10/9 | Programming basics                    |   [Slides 14](slides/14_environment-scope.html){.label .label-green}       |          |     |
|  9   | M 10/14 | Programming basics                    |  [Slides 15](slides/15_data-analysis-functions.html){.label .label-green}                                                                           |                                                               |  [Lab 06](labs/06_lab.html){.label .label-red}
|      | W 10/16 | Simulations                           |  [Slides 16](slides/16_debugging.html){.label .label-green}          |  |          |     |
|  10  | M 10/21 | Simulations                           |  [Slides 17](slides/17_simulations.html){.label .label-green}          |          |     |
|      | W 10/23 | Simulations                           |   [Slides 18](slides/18_more-simulations.html){.label .label-green}          |   [Check-in 06](checkins/06_checkin.html){.label .label-purple}         |     |
|  11  | M 10/28  | Statistical inference                 |  [Slides 19](slides/20_confidence-intervals.html){.label .label-green}     |          |     |
|      | W 10/30 | Statistical inference                 |       |       | [Lab 07](labs/07_lab.html){.label .label-red}       |
|  12  | M 11/4 | Simulation-based inference                  |[Slides 20](slides/19_simulation-based-inference.html){.label .label-green}         |          |     |
|      | W 11/6 | Simulation-based inference            |   [Slides 21](slides/21_hypothesis-testing.html){.label .label-green}      |           |     |
|  13  | M 11/11 | *Veterans' Day - No class*                           |        |          |     |
|      | W 11/13 | Hypothesis Testing                          |    [Slides 22](slides/22_hypothesis-testing-II.html){.label .label-green}    |   [Check-in 07](checkins/07_checkin.html){.label .label-purple}       | [Lab 08](labs/08_lab.html){.label .label-red}     |
|  14  | M 11/18 | Hypothesis Testing                         |  [Slides 22](slides/23_hypothesis-testing-III.html){.label .label-green}      |          |     |
|      | W 11/20  | Regression                         |  [Slides 22](slides/24_linear-reression.html){.label .label-green}        |          |     |
|  15  | M 11/25  | Regression      |        |          |     |
|      | W 11/27  | *Thanksgiving - No class*     |        |          |     |
|  16  | M 12/2  | Prediction                |        |          |     |
|      | W 12/4 | Prediction                  |        |          |     |
|  17  | M 12/9  | Review                   |        |          |     |
|   18   | M 12/16 | *Final exam*                   |        |          |     |
:::

```{r echo = FALSE}
knitr::knit_exit()
```

|      |      |       | Prepare | Slides |                    AE                    | Labs | HW  | Exam | Project |
|--------|--------|--------|:------:|:------:|:------:|:------:|:------:|:------:|:------:|
| Week | Date | Topic |   📖    |   🖥️   | 📋 [Lab 01](hello){.label .label-purple} |  ✍️  |     |      |         |
