---
title: "Lab 7"
author: "YOUR NAME HERE"
format: 
  html:
    embed-resources: true
    code-tools: true
    code-summary: "Code"
---

Remember, **follow the instructions below and use R Markdown to create an html document with your code and answers to the following questions.** You may find a template file by clicking "Code" in the top right corner of this page.

## A. Random sampling in R

1. In your own words, explain the difference between `dnorm()`, `pnorm()`, `qnorm()`, and `rnorm()`.

2. Suppose we simulate `x <- runif(1)`. What is the distribution of `qnorm(x)`?

3. Suppose we simulate `x <- rnorm(1)`. What is the distribution of `pnorm(x)`?

## B. Simulating a dice-rolling experiment

4. Suppose we roll a fair die three times. Let $X$ be the sum of the two lowest rolls. Use simulation to estimate $E(X)$.

## C. Simulating *Squid Game*

The TV show Squid Game features a game in which participants must cross a bridge of eighteen pairs of glass stepping stones. To cross the bridge, you must jump from one pair of stones to the next. However, within each pair, one of the glass stones is strong enough to hold a person’s weight, while one of the stones will break if someone jumps onto it and the player will fall to their death. The participants do not know which stones are safe and which stones will break.

```{r}
#| engine: 'tikz'
#| fig-align: "center"
#| fig-height: 25
#| echo: false
\begin{tikzpicture}

\node[draw, rotate=90] at (0.25, .55){START};
\node[draw, rotate=90] at (18*.75+1, .55){FINISH};
\foreach \i in {1,...,18}
{
  \draw (\i*.75,.75) rectangle (\i*.75+0.5,1.25);
  \draw (\i*.75,0) rectangle (\i*.75+0.5,0.5);
  \node at (.25 + \i*.75, 1.5) {\i};
}

\end{tikzpicture}
```

In the game, participants will take turns trying to cross from the start to the finish. If someone steps on a stone and it breaks, it is not replaced. This means the first person to go has a disadvantage. In order to make it to the end, the first person has to guess successfully which stone in pair 1 is safe, and then guess which stone in pair 2 is safe, and so on. If the first person makes it to the end, the second person can just follow the same path. However, if, for example, the first person falls at pair 5, then the second person can follow the safe path to pair 5 and then try to guess which stone in pair 6 will be safe. The later players will have even more information.

Use simulation to estimate the following probabilities.

5. What is the probability that the first participant reaches the end without falling?

6. If $n=18$ people participate in the game, how many are expected to finish?

7. If $n=10$ people participate in the game, how many are expected to finish?